version: '3.3'

services:
  redis:
    restart: always
    image: redis:latest
    ports:
        - "6379:6379"
    volumes:
        - redisdata:/data
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
        - redis_python_network

  python_devops_app:
    container_name: python_devops_app
    env_file:
        - .env
    build:
        context: .
    restart: always
    ports:
        - '8000:8000'
    entrypoint: ["python3", "hello.py"]
    volumes:
        - .:/usr/src/app
    depends_on:
      - redis
    networks:
        - redis_python_network

volumes:
    redisdata:

networks:
  redis_python_network:
    driver: bridge